Refer to commit description - Add and remove support for several distro versions - Fix SDK not installing...

diff --git a/prereqs-installer b/prereqs-installer
--- a/prereqs-installer
+++ b/prereqs-installer
@@ -19,6 +19,8 @@ install_prereqs() {
     #       Distribution version.
     #   $3 - required
     #       OpenJDK version.
+    #   $4 - optional
+    #       True if dotnet preferences must be set.
     ####
 
     echo "Installing .NET Core..."
@@ -27,10 +29,35 @@ install_prereqs() {
     sudo dpkg -i packages-microsoft-prod.deb
     sudo rm -f packages-microsoft-prod.deb
 
+    ### TODO: Provide better comments to explain this section
+    if [[ $4 = true ]]; then
+        if hash dotnet &>/dev/null && [[ ! $(dotnet --version &>/dev/null) ]]; then
+            echo "${_YELLOW}While the .NET runtime is installed, the .NET SDK is not${_NC}"
+            echo "Uninstalling existing .NET Core 6.0 installation..."
+            sudo apt remove dotnet-sdk-6.0 -y
+            sudo apt autoremove -y
+
+            if [[ ! -f /etc/apt/preferences.d/custom-dotnet.pref ]]; then
+                echo "Upating prefered .NET Core install method..."
+
+                {
+                    echo -e "Explanation: https://github.com/dotnet/core/issues/7699" \
+                        "\nPackage: *" \
+                        "\nPin: origin \"packages.microsoft.com\"" \
+                        "\nPin-Priority: 1001" | sudo tee /etc/apt/preferences.d/custom-dotnet.pref
+                } || {
+                    echo "${_RED}Failed to create" \
+                        "'/etc/apt/preferences.d/custom-dotnet.pref'${_NC}" >&2
+                    exit 1
+                }
+
+                echo "Reinstalling .NET Core..."
+            fi
+        fi
+    fi
+
     ## Install the SDK.
-    sudo apt-get update
-    sudo apt-get install -y apt-transport-https \
-        && sudo apt-get update \
+    sudo apt-get update \
         && sudo apt-get install -y dotnet-sdk-6.0
 
     ## Install Java.
@@ -39,7 +66,7 @@ install_prereqs() {
 
     ## Other prerequisites.
     echo "Installing other prerequisites..."
-    sudo apt-get install redis-server git ccze -y
+    sudo apt-get install redis-server git ccze apt-transport-https -y
 }
 
 unsupported() {
@@ -64,43 +91,20 @@ read -rp "We will now install Mewdeko's prerequisites. Press [Enter] to continue
 
 if [[ $_DISTRO = "ubuntu" ]]; then
     case "$_VER" in
-        18.04|20.04|22.04) install_prereqs "ubuntu" "$_VER" "openjdk-17-jdk" ;;
-        *)                 unsupported ;;
+        22.04)       install_prereqs "ubuntu" "$_VER" "openjdk-17-jdk" "true" ;;
+        18.04|20.04) install_prereqs "ubuntu" "$_VER" "openjdk-17-jdk" ;;
+        *)           unsupported ;;
     esac
 elif [[ $_DISTRO = "debian" ]]; then
     case "$_SVER" in
-        11) install_prereqs "debian" "11" "openjdk-17-jdk" ;;
-        10) install_prereqs "debian" "10" "openjdk-11-jdk" ;;
-        9)
-            echo "Installing .NET Core..."
-            ## Microsoft package signing key.
-            curl https://packages.microsoft.com/keys/microsoft.asc | gpg \
-                --dearmor > microsoft.asc.gpg
-            sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
-            curl -sO https://packages.microsoft.com/config/debian/9/prod.list
-            sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
-            sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
-            sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
-
-            ## Install the SDK.
-            sudo apt-get update
-            sudo apt-get install -y apt-transport-https \
-                && sudo apt-get update \
-                && sudo apt-get install -y dotnet-sdk-6.0
-
-            ## Install Java.
-            echo "Installing 'openjdk-11-jdk'..."
-            sudo apt install openjdk-11-jdk -y
-
-            ## Other prerequisites.
-            echo "Installing other prerequisites..."
-            sudo apt-get install redis-server git ccze -y
-            ;;
+        11) install_prereqs "debian" "$_SVER" "openjdk-17-jdk" ;;
+        10) install_prereqs "debian" "$_SVER" "openjdk-11-jdk" ;;
         *)  unsupported ;;
     esac
 elif [[ $_DISTRO = "linuxmint" ]]; then
     case "$_SVER" in
-        19|20) install_prereqs "ubuntu" "$_VER" "openjdk-17-jdk" ;;
+        21) install_prereqs "ubuntu" "22.04" "openjdk-17-jdk" "true" ;;
+        20) install_prereqs "ubuntu" "20.04" "openjdk-17-jdk" ;;
         *)     unsupported ;;
     esac
 fi
